
wycg:
  log-path: c:/tmp/si/log

udp:
  port: 6666

related-process-program:
  netty:
    server:
      port: 7777

  # 待执行的外部程序路径，多个以分号隔开，最后一个加分号。路径有空格请加引号 java -jar D:\testcmdstdrecive-0.0.1-SNAPSHOT.jar
  execute:
    external-program-paths: java -jar D:\testcmdstdrecive-0.0.1-SNAPSHOT.jar;D:\1.txt;

  report-message:
    cron: 0/1 * * * * ?
    #cron: 0 5 0 * * ?      # 每日零点5分执行一次


logging:
  file:
    name: ${wycg.log-path}/autoExecuteProgram-relatedProcessProgram-app.log
    max-size: 10MB
    max-history: 10
  level:
    xdsei:
      wycg:
        autoExecuteProgram: trace